fix path to lua script (accept local or global path), let stderr to debug single page (path to assets eg)

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -12,6 +12,17 @@ WORKING_DIR=$(pwd)
 OUTPUT_DIR="$WORKING_DIR/public"
 ENV_FILE="$WORKING_DIR/.env"
 
+LOCAL_LUA="$WORKING_DIR/pp-h2-link.lua"
+GLOBAL_LUA="/usr/local/bin/pp-h2-link.lua"
+
+if [[ -f "$LOCAL_LUA" ]]; then
+    LUA_FILTER="$LOCAL_LUA"
+elif [[ -f "$GLOBAL_LUA" ]]; then
+    LUA_FILTER="$GLOBAL_LUA"
+else
+    echo "Error: Lua filter pp-h2-link.lua (for printing to HTML Single Page) not found."
+    exit 1
+fi
 
 # == FUNCTIONS ==
 
@@ -57,7 +68,10 @@ function mdslide2htmlsingle(){
     echo "Local stylesheet (style.css) created"
   fi
 
-	pandoc $1 -f markdown+tex_math_double_backslash -t html5 -s -o ${OUTPUT_DIR}/${filename}.html --toc --toc-depth=2 --lua-filter pp-h2-link.lua --standalone  --strip-comments --mathml --css "$WORKING_DIR"/style.css --self-contained
+	pandoc $1 -f markdown+tex_math_double_backslash -t html5 -s \
+     -o ${OUTPUT_DIR}/${filename}.html \
+    --toc --toc-depth=2 \
+    --lua-filter "$LUA_FILTER" --standalone  --strip-comments --mathml --css "$WORKING_DIR"/style.css --self-contained
 }
 
 # Print standard Markdown document to PDF
@@ -187,7 +201,8 @@ for file in "${SOURCES_SLIDES[@]}"; do
 
     if $do_print_html_single; then
         echo "Printing $base to HTML Single Page ..."
-        mdslide2htmlsingle "$file" 2>/dev/null
+        #mdslide2htmlsingle "$file" 2>/dev/null
+        mdslide2htmlsingle "$file"
     fi
 
     if $do_print_pdf; then
