fix #12: change config file name, add init option, add no ftp option

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -7,10 +7,10 @@
 # This program uses and requires marp, pandoc and lftp.
 
 # == ALIASES ==
-
+ENV_FILE_FILENAME="config.pp"
 WORKING_DIR=$(pwd)
 OUTPUT_DIR="$WORKING_DIR/public"
-ENV_FILE="$WORKING_DIR/.env"
+ENV_FILE="$WORKING_DIR/$ENV_FILE_FILENAME"
 
 LOCAL_LUA="$WORKING_DIR/pp-h2-link.lua"
 GLOBAL_LUA="/usr/local/bin/pp-h2-link.lua"
@@ -25,6 +25,44 @@ else
 fi
 
 # == FUNCTIONS ==
+
+function init_directory(){
+	echo "Init..."
+	echo "Creating a config file $ENV_FILE_FILENAME"
+	cat << EOF > "$ENV_FILE_FILENAME"
+
+#slide-decks
+SOURCES_SLIDES=(
+)
+
+#standalone documents
+SOURCES_DOCS=(
+)
+
+#Printing: Formats printed by default
+do_print_html_single=true
+do_print_html_deck=true
+do_print_pdf=false
+do_print_epub=false
+
+#Publishing: enable/disable
+do_publish_on_ftp_server=false
+
+#Publishing: Prints published by default
+do_publish_html_single=true
+do_publish_html_pdf=true
+do_publish_html_deck=false
+do_publish_html_epub=false
+
+#FTP Credentials
+FTP_HOST=""
+FTP_USER=""
+FTP_PASS=""
+REMOTE_DIR=""
+
+EOF
+	echo "Done"
+}
 
 function show_help() {
     cat <<EOF
@@ -41,6 +79,7 @@ Options:
   --no-epub           Ne pas générer EPUB
   --slides-only       Seulement HTML (Deck + Single Page)
   --clean             Supprime tout le contenu publié (pas les sources ;))
+  --init	      Initialise le répertoire (fichier config.pp)
   -h, --help          Afficher ce message
 EOF
     exit 0
@@ -128,13 +167,6 @@ function md2htmlsingle(){
 
 # == BEGINNING OF THE SCRIPT ==
 
-#Load options (FTP credentials, print and publish formats)
-if [[ -f "$ENV_FILE" ]]; then
-    source "$ENV_FILE"
-else
-    echo "Error: .env not found in $WORKING_DIR."
-    exit 1
-fi
 
 # Handle user options
 while [ $# -gt 0 ]; do
@@ -158,6 +190,10 @@ while [ $# -gt 0 ]; do
             do_print_epub=false
             ;;
 
+        --no-ftp)
+          do_publish_on_ftp_server=false
+          ;;
+
         --ftp)
           do_publish_on_ftp_server=true
           ;;
@@ -176,6 +212,12 @@ while [ $# -gt 0 ]; do
             exit 0
             ;;
 
+	 --init)
+		 echo "Init print-publish config file"
+		 init_directory
+		 exit 0
+		 ;;
+
         -h|--help) show_help ;;
         *)
             echo "Unknown option : $1" >&2
@@ -184,6 +226,16 @@ while [ $# -gt 0 ]; do
     esac
     shift
 done
+
+#Load options (FTP credentials, print and publish formats)
+if [[ -f "$ENV_FILE" ]]; then
+    source "$ENV_FILE"
+else
+    echo "Error: $ENV_FILE_FILENAME not found in $WORKING_DIR."
+    echo "Create a configuration file $ENV_FILE_FILENAME"
+    echo "Use --help for help"
+    exit 1
+fi
 
 # Print SOURCES_SLIDES to HTML slide-deck, HTML Single Page, PDF and Epub
 
