fix bug, cli options not overriding anymore config file options

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -165,6 +165,16 @@ function md2htmlsingle(){
 
 # == BEGINNING OF THE SCRIPT ==
 
+#Load options from configuration file
+if [[ -f "$ENV_FILE" ]]; then
+    source "$ENV_FILE"
+else
+    echo "Error: $ENV_FILE_FILENAME not found in $WORKING_DIR."
+    echo "Create a configuration file $ENV_FILE_FILENAME"
+    echo "Use --help for help"
+    exit 1
+fi
+
 # Handle user options
 while [ $# -gt 0 ]; do
     case "$1" in
@@ -224,16 +234,6 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-#Load options (FTP credentials, print and publish formats)
-if [[ -f "$ENV_FILE" ]]; then
-    source "$ENV_FILE"
-else
-    echo "Error: $ENV_FILE_FILENAME not found in $WORKING_DIR."
-    echo "Create a configuration file $ENV_FILE_FILENAME"
-    echo "Use --help for help"
-    exit 1
-fi
-
 # Print SOURCES_SLIDES to HTML slide-deck, HTML Single Page, PDF and Epub
 
 # Prexif all sources.
@@ -259,8 +259,6 @@ for file in "${SOURCES_SLIDES[@]}"; do
         echo "Warning : file $file does not exist. Skipping file."
         continue
     fi
-
-  
 
     base=$(basename "$file" .md)
 
